name: ntrip
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - bitstring=3.1
  - spyder=5.0
  - sphinx=4.0
  - sphinx-click=3.0
  - pip
  - pip:
    - sphinxcontrib.programoutput
    - sphinx-rtd-theme
variables:
  QT_MAC_WANTS_LAYER: 1
