name: Documentation

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    # strategy:
      # max-parallel: 2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies using conda
      run: |
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
        conda env create --file dev_environment.yml
        source activate ntrip
        hash -r
    - name: Install ntripstreams
        - run: pip install -e .
    -name: Build docs
      - run: |
        sphinx-build -b html ./docs ./docs/_build
        touch ./docs/_build/.nojekyll
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build
        force_orphan: true
