name: Documentation

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup environment
      run: pip install \
        sphinx \
        sphinx-click \
        sphinxcontrib.programoutput \
        sphinx-rtd-theme

    - name: Install project
      run: pip install -e .

    - name: Generate docs
      run: |
        sphinx-build -b html ./docs ./docs/_build
        touch ./docs/_build/.nojekyll

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build
        force_orphan: true
